### ISSUE TITLE
Why do you need %''

### ISSUE THREAD

**Issue by dmtrrk** [Mariam9/booksite1#1]

**Comment by dmtrrk** [comment]
.search-result {
    width: 80%; ????
    margin: 30px; ????
    overflow: hidden; ????
}

.search-result ul li {
    float: left;
    width: 16%; ????
    margin: 2% 17px; ????
}

.search-result ul li a img {
    max-width: 100%; ???
}

**Comment by Mariam9** [comment]
Because it's adaptive CSS gallery. All adaptive markup should be in % as they say

**Comment by dmtrrk** [comment]
All adaptive markup should be first of all adaptive. And you should clarify what exactly "adaptive" in your markup.
IF you need to set FLUENT size for some element, you CAN use %.
But if you don't need - "why do you need %?"
Gallery item have a fixed size.
Gallery container don't need a size at all as it takes all the free space.
So gallery should take all the available space. Each gallery item should take some fixed place. And all gallery items should fill all the free space in a gallery container with aligning to the top left (all the necessary ызфсу by stretching gallery container to the bottom).
You can try to convert your markup to % (but start from header, sidebar, footer). And their size will change according to the window size. But is that what you want?

**Comment by dmtrrk** [comment]
- try to remove all mentioned '%'
- try to set margin only to left/top (your markup should align left and top, so you even don't need bottom/right margins as it will add undefined resizing behavior)
- as you have fixed panel which overlap your gallery, so you can simply add some margin/padding only to Top, that will add indent betweensearch bar and gallery.
- are you sure you have images of different size? or that should be a same-level thumbs?
- gallery item caption should be a link
- each gallery item should have fixed height/width, no?
